//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLibs.Database.MySql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MySqlValidatorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MySqlValidatorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonLibs.Database.MySql.MySqlValidatorResources", typeof(MySqlValidatorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE DummyProcedureTest
        ///(
        ///	VarCharParam varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
        ///)
        ///BEGIN
        ///	SELECT IntColumn, CharColumn
        ///	FROM DummyTableTest;
        ///END.
        /// </summary>
        internal static string MySqlCreateDummyProcedure {
            get {
                return ResourceManager.GetString("MySqlCreateDummyProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW VARIABLES LIKE &apos;max_allowed_packet&apos;.
        /// </summary>
        internal static string MySqlSelectMaxAllowedPacketSize {
            get {
                return ResourceManager.GetString("MySqlSelectMaxAllowedPacketSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ROUTINE_NAME
        ///FROM INFORMATION_SCHEMA.ROUTINES
        ///WHERE ROUTINE_NAME=@ProcedureName
        ///AND ROUTINE_SCHEMA=database();.
        /// </summary>
        internal static string MySqlSelectNameOfExistingProcedure {
            get {
                return ResourceManager.GetString("MySqlSelectNameOfExistingProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TABLE_NAME
        ///FROM INFORMATION_SCHEMA.TABLES
        ///WHERE TABLE_NAME=@TableName
        ///AND TABLE_SCHEMA=database();.
        /// </summary>
        internal static string MySqlSelectNameOfExistingTable {
            get {
                return ResourceManager.GetString("MySqlSelectNameOfExistingTable", resourceCulture);
            }
        }
    }
}
